name: MansheAI Review

on:
  push:
    branches:
      - main # o la rama 2que2 quieras probar
  pull_request:
    branches:
      - main # o la rama que quieras2 probar

jobs:
  mansheai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run MansheAI Review
        uses: AlmaCRH/mansheai-action@test.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          ai_key: ${{ secrets.CODESTRAL_KEY }}
