name: MansheAI Review

on:
  push:
    branches:
      - main # o la rama que quieras probar
  pull_request:
    branches:
      - main # o la rama que quieras probar

jobs:
  mansheai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run MansheAI Review
        uses: AlmaCRH/mansheai-action@v0.3.6-alpha
        with:
          my_code: ${{ secrets.MY_CODE }}
          ai_key: ${{ secrets.CODESTRAL_KEY }}
